using System.IO;
using System.Reflection;
using System.Text.Json;

namespace TiaPortalTool.Services;

public sealed class BlockManifestEntry
{
    public string BlockName { get; set; } = string.Empty;
    public string GroupPath { get; set; } = string.Empty;
    public string XmlPath { get; set; } = string.Empty;
    public string ProgrammingLanguage { get; set; } = string.Empty;
}

public sealed class BlockExportResult
{
    public IReadOnlyList<BlockManifestEntry> Entries { get; set; } = Array.Empty<BlockManifestEntry>();
    public IReadOnlyList<string> Warnings { get; set; } = Array.Empty<string>();

    /// <summary>ProDiag blocks: generated by TIA from the supervisions, and Openness can't export them. Expected, not a warning.</summary>
    public IReadOnlyList<string> ProDiagBlocks { get; set; } = Array.Empty<string>();
}

public sealed class BlockExportService
{
    private const string ManifestFileName = "blocks_manifest.json";

    public BlockExportResult ExportAll(dynamic plcSoftware, Assembly assembly, string exportDirectory, CancellationToken cancellationToken = default)
    {
        Directory.CreateDirectory(exportDirectory);

        var exportOptionsType = assembly.GetType("Siemens.Engineering.ExportOptions")
            ?? throw new InvalidOperationException("Siemens.Engineering.ExportOptions type not found.");
        var withDefaults = Enum.Parse(exportOptionsType, "WithDefaults");

        var entries = new List<BlockManifestEntry>();
        var warnings = new List<string>();
        var proDiag = new List<string>();
        ExportGroup(plcSoftware.BlockGroup, string.Empty, exportDirectory, withDefaults, entries, warnings, proDiag, cancellationToken);

        var manifestPath = Path.Combine(exportDirectory, ManifestFileName);
        File.WriteAllText(manifestPath, JsonSerializer.Serialize(entries, new JsonSerializerOptions { WriteIndented = true }));

        return new BlockExportResult { Entries = entries, Warnings = warnings, ProDiagBlocks = proDiag };
    }

    public static IReadOnlyList<BlockManifestEntry> LoadManifest(string exportDirectory)
    {
        var manifestPath = Path.Combine(exportDirectory, ManifestFileName);
        if (!File.Exists(manifestPath))
        {
            return Array.Empty<BlockManifestEntry>();
        }

        return JsonSerializer.Deserialize<List<BlockManifestEntry>>(File.ReadAllText(manifestPath)) ?? new();
    }

    private static void ExportGroup(dynamic group, string groupPath, string exportDirectory, dynamic exportOptions, List<BlockManifestEntry> entries, List<string> warnings, List<string> proDiag, CancellationToken cancellationToken)
    {
        foreach (dynamic block in group.Blocks)
        {
            cancellationToken.ThrowIfCancellationRequested();
            string blockName = "(unknown)";
            try
            {
                blockName = block.Name;
                var entry = ExportBlock(block, blockName, groupPath, exportDirectory, exportOptions);
                entries.Add(entry);
            }
            catch (Exception ex)
            {
                var reason = Describe(ex);
                if (reason.IndexOf("ProDiag", StringComparison.OrdinalIgnoreCase) >= 0)
                {
                    proDiag.Add(string.IsNullOrEmpty(groupPath) ? blockName : $"{groupPath}/{blockName}");
                }
                else
                {
                    warnings.Add($"Skipped block '{blockName}'{(string.IsNullOrEmpty(groupPath) ? string.Empty : $" in '{groupPath}'")}: {reason}");
                }
            }
        }

        foreach (dynamic subGroup in group.Groups)
        {
            string subPath = string.IsNullOrEmpty(groupPath) ? (string)subGroup.Name : $"{groupPath}/{subGroup.Name}";
            ExportGroup(subGroup, subPath, exportDirectory, exportOptions, entries, warnings, proDiag, cancellationToken);
        }
    }

    private static BlockManifestEntry ExportBlock(dynamic block, string blockName, string groupPath, string exportDirectory, dynamic exportOptions)
    {
        string language = block.ProgrammingLanguage.ToString();

        string folder = string.IsNullOrEmpty(groupPath)
            ? exportDirectory
            : Path.Combine(exportDirectory, SanitizePath(groupPath));
        Directory.CreateDirectory(folder);

        string safeName = SanitizeFileName(blockName);
        string xmlPath = Path.Combine(folder, $"{safeName}.xml");
        if (File.Exists(xmlPath))
        {
            // Export() refuses to overwrite an existing file rather than replacing it,
            // so a stale file from an earlier/partial run would otherwise block re-export.
            File.Delete(xmlPath);
        }
        block.Export(new FileInfo(xmlPath), exportOptions);

        return new BlockManifestEntry
        {
            BlockName = blockName,
            GroupPath = groupPath,
            XmlPath = xmlPath,
            ProgrammingLanguage = language
        };
    }

    /// <summary>
    /// The reason on one line. Openness errors stack "Error when calling method ..." lines over the real cause,
    /// which is the last line, so that's the one kept.
    /// </summary>
    private static string Describe(Exception ex)
    {
        var message = ex is System.Reflection.TargetInvocationException { InnerException: { } inner } ? inner.Message : ex.Message;
        var lines = message.Split(new[] { '\r', '\n' }, StringSplitOptions.RemoveEmptyEntries).Select(l => l.Trim()).Where(l => l.Length > 0).ToList();
        return lines.Count == 0 ? message : lines[lines.Count - 1];
    }

    private static string SanitizeFileName(string name)
    {
        foreach (var c in Path.GetInvalidFileNameChars())
        {
            name = name.Replace(c, '_');
        }
        return name;
    }

    private static string SanitizePath(string path) =>
        string.Join("/", path.Split('/').Select(SanitizeFileName));
}
