using ClosedXML.Excel;
using System.IO;
using System.Reflection;
using System.Text.Json;

namespace TiaPortalTool.Services;

public sealed class WorkbookExportService
{
    private const string ManifestFileName = "workbooks_manifest.json";

    public WorkbookExportResult ExportAll(dynamic plcSoftware, Assembly assembly, string exportDirectory, bool exportTags, bool exportBlocks, bool compileBeforeExport, IProgress<string>? progress = null, CancellationToken cancellationToken = default)
    {
        Directory.CreateDirectory(exportDirectory);

        var manifest = new List<WorkbookManifestEntry>();
        var messages = new List<string>();
        var warnings = new List<string>();
        var workbooks = new Dictionary<string, WorkbookBuilder>(StringComparer.OrdinalIgnoreCase);

        WorkbookBuilder GetWorkbook(string key, string fileName)
        {
            if (!workbooks.TryGetValue(key, out var builder))
            {
                builder = new WorkbookBuilder(Path.Combine(exportDirectory, fileName));
                workbooks[key] = builder;
            }
            return builder;
        }

        if (exportTags)
        {
            progress?.Report("Reading tag tables...");
            var tagExportService = new TagExportService();
            var systemWorkbook = GetWorkbook(string.Empty, "System.xlsx");
            foreach (var table in tagExportService.CollectTagTables(plcSoftware))
            {
                cancellationToken.ThrowIfCancellationRequested();
                systemWorkbook.AddTagSheet(table, manifest);
            }
        }

        if (exportBlocks)
        {
            // Export() refuses to touch any block/UDT whose compiled state is stale relative
            // to a changed PLC data type ("Inconsistent blocks and PLC data types (UDT) cannot
            // be exported"). Compiling the whole PLC software first resolves that consistency
            // state so those blocks become exportable.
            if (compileBeforeExport)
            {
                var compileMessages = new List<string>();
                if (PlcCompiler.CompileAll(plcSoftware, assembly, compileMessages, progress))
                {
                    messages.AddRange(compileMessages);
                }
                else
                {
                    warnings.Add("Pre-export compile finished with errors. Some blocks may still fail to export:");
                    warnings.AddRange(compileMessages);
                }
            }

            cancellationToken.ThrowIfCancellationRequested();
            progress?.Report("Exporting blocks...");
            var blockExportService = new BlockExportService();
            var xmlDir = Path.Combine(exportDirectory, "_blocks_xml");
            var blockResult = blockExportService.ExportAll(plcSoftware, assembly, xmlDir, cancellationToken);
            warnings.AddRange(blockResult.Warnings);
            if (blockResult.ProDiagBlocks.Count > 0)
            {
                messages.Add($"Not exported (expected): {string.Join(", ", blockResult.ProDiagBlocks)}. These ProDiag blocks are generated by "
                             + "TIA Portal from the supervisions and rebuilt when it compiles; Openness can't export them.");
            }

            foreach (var entry in blockResult.Entries)
            {
                cancellationToken.ThrowIfCancellationRequested();
                BlockXmlData data;
                try
                {
                    data = BlockXmlReader.Read(entry.XmlPath, entry.BlockName, entry.ProgrammingLanguage);
                }
                catch (Exception ex)
                {
                    warnings.Add($"Could not parse exported XML for '{entry.BlockName}': {ex.Message}");
                    continue;
                }

                string topGroup = string.IsNullOrEmpty(entry.GroupPath) ? string.Empty : entry.GroupPath.Split('/')[0];
                string fileName = topGroup.Length == 0 ? "System.xlsx" : $"{SanitizeFileName(topGroup)}.xlsx";
                var workbook = GetWorkbook(topGroup, fileName);

                string remainder = topGroup.Length == 0 || entry.GroupPath.Length <= topGroup.Length
                    ? string.Empty
                    : entry.GroupPath.Substring(topGroup.Length + 1);

                workbook.AddBlockSheet(entry, data, remainder, manifest);
            }
        }

        cancellationToken.ThrowIfCancellationRequested();
        progress?.Report("Writing workbooks...");
        var paths = new List<string>();
        foreach (var workbook in workbooks.Values)
        {
            if (workbook.HasContent)
            {
                workbook.Save();
                paths.Add(workbook.Path);
            }
        }

        File.WriteAllText(
            Path.Combine(exportDirectory, ManifestFileName),
            JsonSerializer.Serialize(manifest, new JsonSerializerOptions { WriteIndented = true }));

        return new WorkbookExportResult { WorkbookPaths = paths, Messages = messages, Warnings = warnings };
    }

    private static string SanitizeFileName(string name)
    {
        foreach (var c in Path.GetInvalidFileNameChars())
        {
            name = name.Replace(c, '_');
        }
        return name;
    }

    private sealed class WorkbookBuilder
    {
        public string Path { get; }
        public bool HasContent { get; private set; }

        private readonly XLWorkbook _workbook = new();
        private readonly HashSet<string> _usedSheetNames = new(StringComparer.OrdinalIgnoreCase);

        public WorkbookBuilder(string path) => Path = path;

        public void AddTagSheet(TagTableData table, List<WorkbookManifestEntry> manifest)
        {
            string sheetName = MakeUniqueSheetName(table.TableName);
            var ws = _workbook.Worksheets.Add(sheetName);
            HasContent = true;

            var languages = table.Languages;
            ws.Cell(1, 1).Value = "Name";
            ws.Cell(1, 2).Value = "DataType";
            ws.Cell(1, 3).Value = "Address";
            for (int i = 0; i < languages.Count; i++)
            {
                ws.Cell(1, 4 + i).Value = "Comment:" + languages[i];
            }
            ws.Row(1).Style.Font.Bold = true;

            int row = 2;
            foreach (var tagRow in table.Rows)
            {
                ws.Cell(row, 1).Value = tagRow.Name;
                ws.Cell(row, 2).Value = tagRow.DataType;
                ws.Cell(row, 3).Value = tagRow.Address;
                for (int i = 0; i < languages.Count; i++)
                {
                    ws.Cell(row, 4 + i).Value = tagRow.Comments.TryGetValue(languages[i], out var v) ? v : string.Empty;
                }
                row++;
            }
            ws.Columns().AdjustToContents();

            manifest.Add(new WorkbookManifestEntry
            {
                WorkbookPath = Path,
                SheetName = sheetName,
                Kind = "Tag",
                TagTableName = table.TableName,
                TagGroupPath = table.GroupPath,
                Languages = languages
            });
        }

        public void AddBlockSheet(BlockManifestEntry entry, BlockXmlData data, string groupRemainder, List<WorkbookManifestEntry> manifest)
        {
            string baseName = string.IsNullOrEmpty(groupRemainder) ? entry.BlockName : $"{groupRemainder.Replace('/', '_')}_{entry.BlockName}";
            string sheetName = MakeUniqueSheetName(baseName);
            var ws = _workbook.Worksheets.Add(sheetName);
            HasContent = true;

            var languages = data.AllLanguages();

            int row = 1;
            ws.Cell(row, 1).Value = $"Block: {entry.BlockName} ({entry.ProgrammingLanguage})";
            ws.Cell(row, 1).Style.Font.Bold = true;
            row++;

            if (data.IsTextual)
            {
                ws.Cell(row, 1).Value = "SCL/STL block — read-only source preview. Comment editing for this language "
                    + "is not supported yet; edits made to this sheet will NOT be reimported.";
                ws.Cell(row, 1).Style.Font.FontColor = XLColor.Red;
                row += 2;

                ws.Cell(row, 1).Value = "Block comment";
                ws.Cell(row, 1).Style.Font.Bold = true;
                row++;
                row = WriteLanguageTable(ws, row, languages, data.BlockComment);
                row++;

                foreach (var rung in data.Rungs)
                {
                    ws.Cell(row, 1).Value = $"--- Network {rung.Number} (read-only source preview) ---";
                    ws.Cell(row, 1).Style.Font.Bold = true;
                    row++;
                    // Excel caps a cell at 32,767 chars; large networks spill over multiple rows.
                    foreach (var chunk in SplitForCells(rung.SclPreview ?? string.Empty))
                    {
                        ws.Cell(row, 1).Value = chunk;
                        ws.Cell(row, 1).Style.Alignment.WrapText = true;
                        row++;
                    }
                    row++;
                }

                manifest.Add(new WorkbookManifestEntry
                {
                    WorkbookPath = Path,
                    SheetName = sheetName,
                    Kind = "BlockReadOnly",
                    BlockName = entry.BlockName,
                    BlockGroupPath = entry.GroupPath,
                    XmlPath = entry.XmlPath,
                    Languages = languages,
                    RungCount = data.Rungs.Count
                });
                return;
            }

            ws.Cell(row, 1).Value = "Block comment";
            ws.Cell(row, 1).Style.Font.Bold = true;
            row++;
            row = WriteLanguageTable(ws, row, languages, data.BlockComment);
            row++;

            ws.Cell(row, 1).Value = "Rung";
            for (int i = 0; i < languages.Count; i++) ws.Cell(row, 2 + i).Value = "Title:" + languages[i];
            for (int i = 0; i < languages.Count; i++) ws.Cell(row, 2 + languages.Count + i).Value = "Comment:" + languages[i];
            ws.Row(row).Style.Font.Bold = true;
            row++;

            foreach (var rung in data.Rungs)
            {
                ws.Cell(row, 1).Value = rung.Number;
                for (int i = 0; i < languages.Count; i++)
                    ws.Cell(row, 2 + i).Value = rung.Title.TryGetValue(languages[i], out var t) ? t : string.Empty;
                for (int i = 0; i < languages.Count; i++)
                    ws.Cell(row, 2 + languages.Count + i).Value = rung.Comment.TryGetValue(languages[i], out var c) ? c : string.Empty;
                row++;
            }
            ws.Columns().AdjustToContents();

            manifest.Add(new WorkbookManifestEntry
            {
                WorkbookPath = Path,
                SheetName = sheetName,
                Kind = "BlockEditable",
                BlockName = entry.BlockName,
                BlockGroupPath = entry.GroupPath,
                XmlPath = entry.XmlPath,
                Languages = languages,
                RungCount = data.Rungs.Count
            });
        }

        public void Save() => _workbook.SaveAs(Path);

        private static int WriteLanguageTable(IXLWorksheet ws, int row, List<string> languages, Dictionary<string, string> values)
        {
            ws.Cell(row, 1).Value = "Language";
            ws.Cell(row, 2).Value = "Text";
            ws.Row(row).Style.Font.Bold = true;
            row++;
            foreach (var lang in languages)
            {
                ws.Cell(row, 1).Value = lang;
                ws.Cell(row, 2).Value = values.TryGetValue(lang, out var v) ? v : string.Empty;
                row++;
            }
            return row;
        }

        private const int MaxCellLength = 32767;

        /// <summary>Splits text into chunks that fit in one Excel cell, preferring line boundaries.</summary>
        private static IEnumerable<string> SplitForCells(string text)
        {
            if (text.Length <= MaxCellLength)
            {
                yield return text;
                yield break;
            }

            int start = 0;
            while (start < text.Length)
            {
                int remaining = text.Length - start;
                if (remaining <= MaxCellLength)
                {
                    yield return text.Substring(start);
                    yield break;
                }

                int breakAt = text.LastIndexOf('\n', start + MaxCellLength - 1, MaxCellLength);
                int length = breakAt >= start ? breakAt - start + 1 : MaxCellLength;
                yield return text.Substring(start, length).TrimEnd('\r', '\n');
                start += length;
            }
        }

        private string MakeUniqueSheetName(string baseName)
        {
            string sanitized = SanitizeSheetName(baseName);
            if (sanitized.Length > 31) sanitized = sanitized.Substring(0, 31);

            string candidate = sanitized;
            int suffix = 1;
            while (_usedSheetNames.Contains(candidate))
            {
                string suffixText = "_" + suffix;
                int maxBaseLength = 31 - suffixText.Length;
                candidate = (sanitized.Length > maxBaseLength ? sanitized.Substring(0, maxBaseLength) : sanitized) + suffixText;
                suffix++;
            }

            _usedSheetNames.Add(candidate);
            return candidate;
        }

        private static string SanitizeSheetName(string name)
        {
            foreach (var c in new[] { '\\', '/', '?', '*', '[', ']', ':' })
            {
                name = name.Replace(c, '_');
            }
            return name;
        }
    }
}
